trigger:
- master

pool:
  vmImage: "ubuntu-latest"

steps:
- script: dotnet build
  displayName: Build project
- script: dotnet test
  displayName: Test project
- script: echo Completed
  displayName: Completed
- script: echo '$(Agent.BuildDirectory)'
  displayName: Build Directory
- script: echo '$(Build.ArtifactStagingDirectory)'
  displayName: Artifact Staging Directory
- script: pwd
  displayName: Print working directory
- script: ls -la
  displayName: Content In Current
- script: ls -la '$(Agent.BuildDirectory)'
  displayName: Content In Agent Build Directory
- script: ls -la '$(Build.SourcesDirectory)'
  displayName: Content In Build Sources Directory
- script: env | sort
  displayName: All env vars
- script: echo '$(mykey)'
- script: echo $(mykey)
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/sample-lib/bin/Debug/netstandard2.0'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-$(Build.BuildId)'
    publishLocation: 'Container'