trigger:
- master

pool:
  vmImage: "ubuntu-latest"

steps:
- script: dotnet build
  displayName: Build project
- script: dotnet test
  displayName: Test project
- script: echo Completed
  displayName: Completed
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'