trigger:
- master

pool:
  vmImage: "ubuntu-latest"

steps:
- script: dotnet build
  displayName: Build project
- script: dotnet test
  displayName: Test project
- script: echo Completed
  displayName: Completed
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Agent.BuildDirectory)'
    includeRootFolder: true
    archiveType: 'tar'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    TargetPath: 
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'